### ISSUE TITLE
AreaDensity doesn't convert to Mass correctly if unit isn't KilogramsPerSquareMeter

### ISSUE THREAD

**Issue by DaveDeCaprio** [garyKeorkunian/squants#116]
You don't notice this with squants itself because it squants only has the 1 AreaDensity type, but I made a couple custom ones for my app and noticed the issue.

I've submitted a pull request for the fix.[https://github.com/garyKeorkunian/squants/pull/115](url)

**Comment by garyKeorkunian** [comment]
Thanks.  Sorry I missed this.  I made one simple change request on the PR.  Once that is addressed, I'll merge and publish.
