### ISSUE TITLE
squants.information and 0.6.1-SNAPSHOT

### ISSUE THREAD

**Issue by gkthiruvathukal** [garyKeorkunian/squants#121]
Hi, I'm working on a project that uses your preliminary support for storage units of measurement. When I started using same, the package was named squants.storage. Now it is squants.information. 

When I try to use your snapshot builds for my own project, https://github.com/LoyolaChicagoCode/blockperf-scala, which does builds for 2.10 and 2.11 of Scala against your 0.6.1-SNAPSHOT, it seems like the 2.10 build for squants has not been updated. This might be because your 2.10 build didn't get pushed to bintray.

Here is where my own build is getting tripped up when trying to build the 2.10.6 version:

```
$ sbt '+ package'
[info] Loading project definition from /Users/gkt/Work/blockperf-scala/project
[info] Set current project to blockperf (in build file:/Users/gkt/Work/blockperf-scala/)
[info] Setting version to 2.10.6
[info] Reapplying settings...
[info] Set current project to blockperf (in build file:/Users/gkt/Work/blockperf-scala/)
[info] Compiling 1 Scala source to /Users/gkt/Work/blockperf-scala/target/scala-2.10/classes...
[error] /Users/gkt/Work/blockperf-scala/src/main/scala/blockperf/Performance.scala:2: object information is not a member of package squants
[error] import squants.information._
[error]                ^
[error] /Users/gkt/Work/blockperf-scala/src/main/scala/blockperf/Performance.scala:16: not found: value Bytes
[error]     val used = Bytes(m) in Megabytes
[error]                ^
[error] /Users/gkt/Work/blockperf-scala/src/main/scala/blockperf/Performance.scala:17: not found: value Bytes
[error]     val free = Bytes(Runtime.getRuntime.freeMemory) in Gigabytes
[error]                ^
[error] /Users/gkt/Work/blockperf-scala/src/main/scala/blockperf/Performance.scala:18: not found: value Bytes
[error]     val total = Bytes(Runtime.getRuntime.totalMemory) in Gigabytes
[error]                 ^
[error] four errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 1 s, completed Mar 10, 2016 3:38:48 PM
```

**Comment by gkthiruvathukal** [comment]
If you want to reproduce this, please checkout my project above and run:

```
git clone https://github.com/LoyolaChicagoCode/blockperf-scala
cd blockperf-scala
sbt '+ package'
```

You'll see errors only for the 2.10 cross build, not 2.11 (which works fine).

**Comment by garyKeorkunian** [comment]
Hello.  I apologize for delay in getting to this.  I initially missed the issue.

The package has been republished and the build you reference above is now compiling OK ( remember to run 'sbt clean' so that you force a new copy of 0.6.1-SNAPSHOT.

In retrospect, due to the package name change, I should have incremented the version.
