### ISSUE TITLE
Cross compile to Scala.js

### ISSUE THREAD

**Issue by rpiaggio** [garyKeorkunian/squants#122]
Thanks for this great library.

I kindly request to publish it cross-compiled to Scala.js so that it can be used in hybrid (Scala/Scala.js) projects.

Thank you!

**Comment by garyKeorkunian** [comment]
Sorry for delay in getting to this.  I initially missed the issue.

I have republished the 0.6.1-SNAPSHOT with cross compile versions for JVM and Scala.js.

Let me know if it doesn't work.

Thanks.

**Comment by rpiaggio** [comment]
HI @garyKeorkunian , sorry I couldn't test until now.

It seems to working just fine, thank you very much!
