### ISSUE TITLE
Irradiance division

### ISSUE THREAD

**Issue by cquiroz** [garyKeorkunian/squants#123]
I wanted to check if this is a bug or is it by design. On Irradiance we can divide by power as in [here](https://github.com/garyKeorkunian/squants/blob/master/shared/src/main/scala/squants/radio/Irradiance.scala#L27)

We can see that the function is defined as
```
def /(that: Power): Area
```

however irradiance is `power/area` and dividing by power doesn't give you area but `1/area`.

Am I missing something?

**Comment by garyKeorkunian** [comment]
@cquiroz Good catch.  That is a bogus conversion. It is in the process of being removed and latest snapshot should be updated soon.

Thanks!
