### ISSUE TITLE
problem with custom DataRateUnit

### ISSUE THREAD

**Issue by csprenger** [garyKeorkunian/squants#135]
why does the following custom DataRateUnit lead to the wrong result?

```
  object GibibytesPerDay extends DataRateUnit {
    val symbol = "GiB/d"
    val conversionFactor = Gibibytes.conversionFactor / Days.conversionFactor
  }
```

manual test code: 

```
    val averageDataRate: DataRate = MebibytesPerSecond(4096)
    println(averageDataRate in MebibytesPerSecond)
    println(averageDataRate in GibibytesPerSecond)
    println(averageDataRate in GibibytesPerDay)
    println( 4 * 60 * 60 * 24)
```

The third line (GibibytesPerDay) is off by a factor of 1000.

It can be corrected by 

```
object GibibytesPerDay extends DataRateUnit {
    val symbol = "GiB/d"
    val conversionFactor = Gibibytes.conversionFactor / (Days.conversionFactor / Seconds.conversionFactor)
  }
```

but it is a bit counterintuitive.

Is there a better way to create custom DataRateUnits ?

**Comment by derekmorr** [comment]
Perhaps a move intuitive way to define your custom DataRateUnit is:

object GibibytesPerDay extends DataRateUnit {
  val symbol = "GiB/d"
  val conversionFactor = Gibibytes.conversionFactor / Time.SecondsPerDay
}

This is similar to how VolumeFlow is defined (in squants/motion/VolumeFlow.scala)

**Comment by csprenger** [comment]
Thanks. That is much better.
