### ISSUE TITLE
Does not save values in the units used to create them

### ISSUE THREAD

**Issue by nornagon** [garyKeorkunian/squants#99]
```
$ sbt console
scala> Kilowatts(1200)
res3: squants.energy.Power = 1.2 MW
scala> Microlitres(20000)
res2: squants.space.Volume = 2.0E-5 m³
```

This is causing havoc with serialization tests in my project (since things don't round-trip from JSON back to JSON).

The README claims that "Quantity values are based in the units used to create them", but this does not seem to be the case.

**Comment by garyKeorkunian** [comment]
Hey Jeremy, sorry I missed this.  I'm some not getting the notifications I should from GitHub.

I will look into this ASAP and let you know what's going on.

**Comment by garyKeorkunian** [comment]
Here is the output I get from the same calls as above:

```scala
scala> Kilowatts(1200)
res0: squants.energy.Power = 1200.0 kW
scala> Microlitres(20000)
res1: squants.space.Volume = 20000.0 µl
```

Which version of squants are you using?

**Comment by nornagon** [comment]
Ah, looks like I was using an old version. I can't seem to test on current master though, because:

```
$ git clone https://github.com/garyKeorkunian/squants
$ cd squants
$ sbt console
scala> import squants._
<console>:10: error: not found: value squants
       import squants._
```

**Comment by garyKeorkunian** [comment]
Yes, master includes a change that supports ScalaJS.

Unfortunately it broke the sbt.console and publish features.  I am working on fixing that now, though I expect I won't have anything ready until next week.

The most recent best code prior to that change is the 0.6.0-SNAPSHOT branch.  If you're pulling down the repo, use that.

If you are using an sbt dependency in another project, I would stick with that version for now, as well.  Also, the most recent pre-release (non-snapshot), 0.5.3, should also work OK for what you are doing.

**Comment by garyKeorkunian** [comment]
@nornagon 

You can make use of the master branch in the console by first changing to the squantsJVM project

```sbt
project squantsJVM
console
```

**Comment by nornagon** [comment]
Great, it's working now. Sorry for the noise!
